# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_programm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_1(object):
    def setupUi_1(self, Dialog_1):
        Dialog_1.setObjectName("Dialog_1")
        Dialog_1.setObjectName("Dialog_1")
        Dialog_1.resize(556, 286)
        Dialog_1.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        Dialog_1.setAutoFillBackground(False)
        Dialog_1.setStyleSheet("background-color: rgba(153, 153, 153, 210);\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog_1)
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("pictures/main_pic.png"))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog_1)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)

        self.retranslateUi(Dialog_1)
        QtCore.QMetaObject.connectSlotsByName(Dialog_1)

    def retranslateUi(self, Dialog_1):
        _translate = QtCore.QCoreApplication.translate
        Dialog_1.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.American Typewriter\'; font-size:18pt;\">Приложение было создано в целях помощи студентам. Предлагаемый функционал с каждой новой версией будет расширяться и дополнятся. Благодаря этой программе есть возможность выполнять различные рутинные и неприятные действия автоматически. </span></p></body></html>"))



